# Generated by Django 5.1 on 2024-08-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('little', 'Little/no exercise'), ('light', 'Light exercise'), ('moderate', 'Moderate exercise (3-5 days/wk)'), ('active', 'Very active (6-7 days/wk)'), ('extra', 'Extra active (very active & physical job)')], default='little', max_length=10),
        ),
    ]
